import type { Case, ConformanceCase } from "../types/case";
import { OAS_VERSIONS } from "../types/openapi";
import type { LibraryMeasurement } from "../types/measurement";
import { ownsStage } from "../types/pipeline";
import {
  CONFORMANCE_OUTCOMES,
  OUTCOME_LABEL,
  OUTCOME_NOTE,
  STAGE_SLOTS,
  conformanceCell,
  valuesCell,
  verdictCell,
} from "./cells";
import { conformanceTallies, matrixFileName, presentVersions } from "./view";

/**
 * What to say beside a version that may not be the code that answered.
 *
 * A local resolution means the installed package's manifest carried the last
 * released version while the tree measured was something else, so the number
 * above it is the release that tree was branched from. Saying nothing here
 * would let a private run read exactly like a published one.
 */
function resolutionNote(measurement: LibraryMeasurement): string {
  if (measurement.libraryResolution.kind === "registry") return "";
  const specifier = measurement.libraryResolution.specifier;
  return (
    ` (installed from ${specifier ?? "a local source"}, so this is the release the` +
    ` measured tree was branched from rather than the code that answered;` +
    ` \`${measurement.provenance.imageId.slice(0, 19)}\` is what tells two such runs apart)`
  );
}

/**
 * Read one library's measurement on its own.
 *
 * The single-library view is the ordinary one rather than a reduced form of the
 * comparison. Nothing here mentions another library or needs one to have been
 * measured, so running the harness against one library produces a report that
 * is complete rather than a matrix with a single column.
 *
 * Scoring happens here rather than in the measurement. The corpus holds the
 * expected verdict and the expected values, adapters are forbidden from seeing
 * them, and a score written into the artifact would put the judgement beyond
 * the reach of anyone re-reading the answer it was derived from.
 */
export function renderLibrary(cases: readonly Case[], measurement: LibraryMeasurement): string {
  const lines: string[] = [];
  const byCase = new Map(measurement.answers.map((answer) => [answer.caseId, answer.result]));

  lines.push(`# \`${measurement.library}\``);
  lines.push("");
  lines.push("Generated by `pnpm render-md`. Everything here derives from");
  lines.push(`\`libraries/${measurement.provenance.slug}.json\`, joined with \`corpus.json\`.`);
  lines.push("");
  lines.push(`Version measured: ${measurement.libraryVersion}${resolutionNote(measurement)}`);
  lines.push("");
  if (measurement.librarySource !== null) {
    // Stated by the container, not resolved or checked here, which is why it
    // is worded as a claim rather than printed as a fact.
    lines.push(`Source, as its container states it: ${measurement.librarySource}`);
    lines.push("");
  }
  lines.push(`Built from: \`adapters/${measurement.provenance.slug}/\``);
  lines.push("");
  lines.push(`Image: \`${measurement.provenance.imageId}\``);
  lines.push("");
  lines.push(`Configuration \`${measurement.configuration.id}\`: ${measurement.configuration.description}`);
  lines.push("");

  lines.push("## What it does for itself");
  lines.push("");
  lines.push("| stage | |");
  lines.push("| --- | --- |");
  for (const slot of STAGE_SLOTS) {
    const owns = ownsStage(measurement.capabilities.stages, slot.stage, slot.location ?? "path");
    lines.push(`| ${slot.label} | ${owns ? "owned" : "caller"} |`);
  }
  lines.push("");
  const declaredVersions = OAS_VERSIONS.filter(
    (version) => measurement.capabilities.oasVersions[version],
  );
  lines.push(
    `Declares its library accepts OpenAPI ${declaredVersions.join(", ")} documents. ` +
      "Cases of other versions render as not asked, and what the version probes saw " +
      "is in [capabilities.md](../capabilities.md).",
  );
  lines.push("");
  lines.push("`caller` means this library requires the stage to have been done already, so");
  lines.push("the specification rules governing it are the caller's to get right. See");
  lines.push("[fitness.md](../fitness.md) for what that means in full.");
  lines.push("");

  for (const version of presentVersions(cases)) {
    const versionCases = cases.filter((c) => c.oasVersion === version);
    const matrixFile = `../${matrixFileName(version)}`;
    const caseLink = (id: string): string => `[\`${id}\`](${matrixFile}#${id})`;
    const conformance = versionCases.filter((c): c is ConformanceCase => c.tier === "conformance");
    const scored = conformance.map((testCase) => {
      const result = byCase.get(testCase.id);
      const cell = conformanceCell(testCase, result);
      return { testCase, result, outcome: cell.outcome, reason: cell.reason };
    });

    lines.push(`## OpenAPI ${version}`);
    lines.push("");
    lines.push("### Conformance");
    lines.push("");
    const tally = conformanceTallies(versionCases, [{ label: measurement.library, measurement }])[0];
    if (tally === undefined) throw new Error("a measurement produced no conformance tally");

    lines.push("The specification settles these, so a failure is attributable and the rule it");
    lines.push(`rests on is quoted with the case in [${matrixFileName(version)}](${matrixFile}).`);
    lines.push("These counts are of one library and say nothing about any other. Every");
    lines.push(`OpenAPI ${version} conformance case falls in one row, including the ones this`);
    lines.push("library was not asked, so the rows sum to the total and the denominator is on");
    lines.push("the page with the numbers.");
    lines.push("");
    lines.push("| result | cases |");
    lines.push("| --- | --- |");
    for (const outcome of CONFORMANCE_OUTCOMES) {
      const count = tally.counts[outcome];
      if (count > 0) lines.push(`| ${OUTCOME_LABEL[outcome]} | ${String(count)} |`);
    }
    lines.push(`| every conformance case | ${String(tally.total)} |`);
    lines.push("");
    for (const outcome of CONFORMANCE_OUTCOMES) {
      if (tally.counts[outcome] > 0) lines.push(`- \`${OUTCOME_LABEL[outcome]}\`: ${OUTCOME_NOTE[outcome]}`);
    }
    lines.push("");

    const failures = scored.filter(
      (entry) => entry.outcome === "failVerdict" || entry.outcome === "failValue",
    );
    if (failures.length > 0) {
      lines.push("#### Cases it did not pass");
      lines.push("");
      lines.push("| case | expected | it answered | values |");
      lines.push("| --- | --- | --- | --- |");
      for (const entry of failures) {
        lines.push(
          `| ${caseLink(entry.testCase.id)} | ${entry.testCase.expected} | ` +
            `${verdictCell(entry.result)} | ${valuesCell(entry.result)} |`,
        );
      }
      lines.push("");
      lines.push(`Each case id links to the case in full, with the rule the expected verdict`);
      lines.push(`rests on quoted beside it. Each row traces to the stored raw output in`);
      lines.push(`\`libraries/${measurement.provenance.slug}.json\` by case id. An inaccurate`);
      lines.push("row can come from the adapter, the case, or the corpus tier, and");
      lines.push("the harness repository's `docs/adding-an-adapter.md` says how to identify it");
      lines.push("and what counts as a fix.");
      lines.push("");
    }

    const notAsked = scored.filter((entry) => entry.outcome === "notApplicable");
    if (notAsked.length > 0) {
      lines.push("#### Cases it was not asked");
      lines.push("");
      const reasonOf = (entry: (typeof notAsked)[number]): string => entry.reason ?? "";
      const stageNotOwned = notAsked.filter((entry) => reasonOf(entry) === "stageNotOwned");
      const inputUnavailable = notAsked.filter(
        (entry) => reasonOf(entry) === "harnessInputUnavailable",
      );
      const other = notAsked.filter(
        (entry) =>
          reasonOf(entry) !== "stageNotOwned" &&
          reasonOf(entry) !== "harnessInputUnavailable",
      );

      if (stageNotOwned.length > 0) {
        lines.push("Stage owned by the caller. An answer would describe the harness's work");
        lines.push("at or downstream of the stage this case probes.");
        lines.push("");
        for (const entry of stageNotOwned) {
          lines.push(`- ${caseLink(entry.testCase.id)} (stageNotOwned)`);
        }
        lines.push("");
      }
      if (inputUnavailable.length > 0) {
        lines.push("Harness input unavailable. This library expects decoded query pairs, and");
        lines.push("constructing them would choose the decoding the corpus exists to measure.");
        lines.push("");
        for (const entry of inputUnavailable) {
          lines.push(`- ${caseLink(entry.testCase.id)} (harnessInputUnavailable)`);
        }
        lines.push("");
      }
      if (other.length > 0) {
        lines.push("Another unsupported boundary. The stored reason beside each case identifies");
        lines.push("whether the document version, library input shape, or adapter stopped it.");
        lines.push("");
        for (const entry of other) {
          lines.push(`- ${caseLink(entry.testCase.id)} (${reasonOf(entry)})`);
        }
        lines.push("");
      }
    }

    const unanswered = scored.filter((entry) => entry.outcome === "unanswered");
    if (unanswered.length > 0) {
      lines.push("#### Cases this measurement holds no answer for");
      lines.push("");
      lines.push(OUTCOME_NOTE.unanswered);
      lines.push("");
      for (const entry of unanswered) lines.push(`- ${caseLink(entry.testCase.id)}`);
      lines.push("");
    }

    lines.push("### Divergence");
    lines.push("");
    lines.push("The specification does not settle these. What it returned is recorded and");
    lines.push("nothing is attributed to it.");
    lines.push("");
    lines.push("| case | verdict | values |");
    lines.push("| --- | --- | --- |");
    for (const testCase of versionCases.filter((c) => c.tier === "divergence")) {
      const result = byCase.get(testCase.id);
      lines.push(
        `| ${caseLink(testCase.id)} | ${verdictCell(result)} | ${valuesCell(result)} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}
