import type { Case, ConformanceCase } from "../types/case";
import { OAS_VERSIONS } from "../types/openapi";
import type { AdapterResult } from "../types/result";
import type { LibraryMeasurement } from "../types/measurement";
import type { ConformanceOutcome } from "./score";
import { score } from "./score";
import { CONFORMANCE_OUTCOMES, conformanceTallies, matrixFileName, presentVersions } from "./view";

/**
 * Read one library's measurement on its own.
 *
 * The single-library view is the ordinary one rather than a reduced form of the
 * comparison. Nothing here mentions another library or needs one to have been
 * measured, so running the harness against one library produces a report that
 * is complete rather than a matrix with a single column.
 *
 * Scoring happens here rather than in the measurement. The corpus holds the
 * expected verdict and the expected values, adapters are forbidden from seeing
 * them, and a score written into the artifact would put the judgement beyond
 * the reach of anyone re-reading the answer it was derived from.
 */
/**
 * What to say beside a version that may not be the code that answered.
 *
 * A local resolution means the installed package's manifest carried the last
 * released version while the tree measured was something else, so the number
 * above it is the release that tree was branched from. Saying nothing here
 * would let a private run read exactly like a published one.
 */
function resolutionNote(measurement: LibraryMeasurement): string {
  if (measurement.libraryResolution.kind === "registry") return "";
  const specifier = measurement.libraryResolution.specifier;
  return (
    ` (installed from ${specifier ?? "a local source"}, so this is the release the` +
    ` measured tree was branched from rather than the code that answered;` +
    ` \`${measurement.provenance.imageId.slice(0, 19)}\` is what tells two such runs apart)`
  );
}

export function renderLibrary(cases: readonly Case[], measurement: LibraryMeasurement): string {
  const lines: string[] = [];
  const byCase = new Map(measurement.answers.map((answer) => [answer.caseId, answer.result]));

  lines.push(`# \`${measurement.library}\``);
  lines.push("");
  lines.push("Generated by `pnpm render-md`. Everything here derives from");
  lines.push(`\`libraries/${measurement.provenance.slug}.json\`, joined with \`corpus.json\`.`);
  lines.push("");
  lines.push(`Version measured: ${measurement.libraryVersion}${resolutionNote(measurement)}`);
  lines.push("");
  if (measurement.librarySource !== null) {
    // Stated by the container, not resolved or checked here, which is why it
    // is worded as a claim rather than printed as a fact.
    lines.push(`Source, as its container states it: ${measurement.librarySource}`);
    lines.push("");
  }
  lines.push(`Built from: \`adapters/${measurement.provenance.slug}/\``);
  lines.push("");
  lines.push(`Image: \`${measurement.provenance.imageId}\``);
  lines.push("");
  lines.push(`Configuration \`${measurement.configuration.id}\`: ${measurement.configuration.description}`);
  lines.push("");

  lines.push("## What it does for itself");
  lines.push("");
  const stages = measurement.capabilities.stages;
  lines.push("| stage | |");
  lines.push("| --- | --- |");
  lines.push(`| routing | ${stages.routing ? "owned" : "caller"} |`);
  lines.push(`| split: path | ${stages.splitting.path ? "owned" : "caller"} |`);
  lines.push(`| split: query | ${stages.splitting.query ? "owned" : "caller"} |`);
  lines.push(`| split: header | ${stages.splitting.header ? "owned" : "caller"} |`);
  lines.push(`| split: cookie | ${stages.splitting.cookie ? "owned" : "caller"} |`);
  lines.push(`| style and explode | ${stages.styleDeserialization ? "owned" : "caller"} |`);
  lines.push(`| content media type | ${stages.contentDeserialization ? "owned" : "caller"} |`);
  lines.push(`| schema validation | ${stages.schemaValidation ? "owned" : "caller"} |`);
  lines.push(`| value exposure | ${stages.valueExposure ? "owned" : "caller"} |`);
  lines.push("");
  const declaredVersions = OAS_VERSIONS.filter(
    (version) => measurement.capabilities.oasVersions[version],
  );
  lines.push(
    `Declares its library accepts OpenAPI ${declaredVersions.join(", ")} documents. ` +
      "Cases of other versions render as not asked, and what the version probes saw " +
      "is in [capabilities.md](../capabilities.md).",
  );
  lines.push("");
  lines.push("`caller` means this library requires the stage to have been done already, so");
  lines.push("the specification rules governing it are the caller's to get right. See");
  lines.push("[fitness.md](../fitness.md) for what that means in full.");
  lines.push("");

  for (const version of presentVersions(cases)) {
    const versionCases = cases.filter((c) => c.oasVersion === version);
    const matrixFile = `../${matrixFileName(version)}`;
    const caseLink = (id: string): string => `[\`${id}\`](${matrixFile}#${id})`;
    const conformance = versionCases.filter((c): c is ConformanceCase => c.tier === "conformance");
    const scored = conformance.map((testCase) => {
      const result = byCase.get(testCase.id);
      return {
        testCase,
        result,
        outcome: result === undefined ? "notApplicable" : score(testCase, result),
      };
    });

    lines.push(`## OpenAPI ${version}`);
    lines.push("");
    lines.push("### Conformance");
    lines.push("");
    const tally = conformanceTallies(versionCases, [{ label: measurement.library, measurement }])[0];
    if (tally === undefined) throw new Error("a measurement produced no conformance tally");

    lines.push("The specification settles these, so a failure is attributable and the rule it");
    lines.push(`rests on is quoted with the case in [${matrixFileName(version)}](${matrixFile}).`);
    lines.push("These counts are of one library and say nothing about any other. Every");
    lines.push(`OpenAPI ${version} conformance case falls in one row, including the ones this`);
    lines.push("library was not asked, so the rows sum to the total and the denominator is on");
    lines.push("the page with the numbers.");
    lines.push("");
    lines.push("| result | cases |");
    lines.push("| --- | --- |");
    for (const outcome of CONFORMANCE_OUTCOMES) {
      const count = tally.counts[outcome];
      if (count > 0) lines.push(`| ${describeOutcome(outcome)} | ${String(count)} |`);
    }
    lines.push(`| every conformance case | ${String(tally.total)} |`);
    lines.push("");

    const failures = scored.filter(
      (entry) => entry.outcome === "failVerdict" || entry.outcome === "failValue",
    );
    if (failures.length > 0) {
      lines.push("#### Cases it did not pass");
      lines.push("");
      lines.push("| case | expected | it answered | values |");
      lines.push("| --- | --- | --- | --- |");
      for (const entry of failures) {
        lines.push(
          `| ${caseLink(entry.testCase.id)} | ${entry.testCase.expected} | ` +
            `${verdictOf(entry.result)} | ${valuesOf(entry.result)} |`,
        );
      }
      lines.push("");
      lines.push(`Each case id links to the case in full, with the rule the expected verdict`);
      lines.push(`rests on quoted beside it. Each row traces to the stored raw output in`);
      lines.push(`\`libraries/${measurement.provenance.slug}.json\` by case id. An inaccurate`);
      lines.push("row can come from the adapter, the case, or the corpus tier, and");
      lines.push("the harness repository's `docs/adding-an-adapter.md` says how to identify it");
      lines.push("and what counts as a fix.");
      lines.push("");
    }

    const notAsked = scored.filter((entry) => entry.outcome === "notApplicable");
    if (notAsked.length > 0) {
      lines.push("#### Cases it was not asked");
      lines.push("");
      lines.push("Not a gap in the measurement. Each is a stage this library leaves to its");
      lines.push("caller, so an answer would describe the harness rather than the library.");
      lines.push("");
      for (const entry of notAsked) {
        const reason =
          entry.result !== undefined && entry.result.outcome === "unsupported"
            ? entry.result.reason
            : "not answered";
        lines.push(`- ${caseLink(entry.testCase.id)} (${reason})`);
      }
      lines.push("");
    }

    lines.push("### Divergence");
    lines.push("");
    lines.push("The specification does not settle these. What it returned is recorded and");
    lines.push("nothing is attributed to it.");
    lines.push("");
    lines.push("| case | verdict | values |");
    lines.push("| --- | --- | --- |");
    for (const testCase of versionCases.filter((c) => c.tier === "divergence")) {
      const result = byCase.get(testCase.id);
      lines.push(
        `| ${caseLink(testCase.id)} | ${verdictOf(result)} | ${valuesOf(result)} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

function describeOutcome(outcome: ConformanceOutcome): string {
  if (outcome === "passVerdictOnly") return "pass (verdict only)";
  if (outcome === "failVerdict") return "FAIL (verdict)";
  if (outcome === "failValue") return "FAIL (value)";
  if (outcome === "notApplicable") return "not asked";
  if (outcome === "libraryError") return "raised instead of answering";
  return outcome === "adapterError" ? "harness error" : outcome;
}

function verdictOf(result: AdapterResult | undefined): string {
  if (result === undefined) return "-";
  if (result.outcome === "unsupported") return `not asked (${result.reason})`;
  if (result.outcome === "adapterError") return "harness error";
  if (result.outcome === "libraryError") return "raised, no verdict";
  return result.outcome;
}

function valuesOf(result: AdapterResult | undefined): string {
  if (result === undefined) return "-";
  if (result.outcome === "unsupported") return "-";
  if (result.outcome === "adapterError" || result.outcome === "libraryError") return "-";
  const observation = result.deserialized;
  if (observation.kind === "unexposed") return "not exposed by this library";
  if (observation.kind === "notReached") return `none reached (${observation.reason})`;
  // A parameter this container could not read is absent from `value` exactly as
  // a parameter the library reported nothing for is, so it is named here rather
  // than left to look like the second.
  const unreadable = Object.keys(observation.unreadable ?? {}).sort();
  const withheld =
    unreadable.length === 0
      ? ""
      : `, and this container could not read ${unreadable.map((name) => `\`${name}\``).join(", ")}`;
  return `\`${JSON.stringify(observation.value)}\`${withheld}`;
}
